
-- Insert program outcome tables
insert into program_outcome_tables (outcome_table_id, outcome_table_display_name, outcome_table_name) values
(1, 'ONDC Registration', 'ONDCRegistration'),
(2, 'ONDC Transaction', 'ONDCTransaction'),
(3, 'Udyam Registration', 'UdyamRegistration'),
(4, 'CGTMSE Transaction', 'CGTMSETransaction'),
(5, 'GeM Transaction','GeMTransaction'),
(6,'TReDS Registration','TReDSRegistration'),
(7,'TReDS Transaction','TReDSTransaction'),
(8,'PMEGP','PMEGP'),
(9,'PMMY','PMMY'),
(10,'PMS','PMS'),
(11, 'IC Scheme', 'ICScheme'),
(12,'NSIC','NSIC'),
(13,'Patents','Patents'),
(14,'GIProduct','GIProduct'),
(15,'Barcode','Barcode'),
(16,'TreadMark','TreadMark'),
(17,'ZEDCertification Bronze','ZEDCertification'),
(18,'ZEDCertification Silver','ZEDCertification'),
(19,'ZEDCertification Gold','ZEDCertification'),
(20,'Lean','Lean'),
(21,'GeM Registration','GeMRegistration'),
(22,'Consortia Tender','ConsortiaTender'),
(23,'OEM','OEM'),
(24,'PMFME Scheme','PMFMEScheme'),
(25,'PM Viswakarma','PMViswakarma'),
(26,'Vendor Development','VendorDevelopment'),
(27,'Sc St Hub','ScStHub'),
(28,'SIDBI Aspire','SIDBIAspire'),
(29,'Design Rights','DesignRights'),
(30,'Copy Rights','CopyRights'),
(31,'Greening Of MSME','GreeningOfMSME'),



